# Generated by Django 6.0.3 on 2026-03-27 06:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('force_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('rank', models.CharField(choices=[('IGP', 'Inspector General of Police'), ('DIGP', 'Deputy IGP'), ('CASP', 'Commissioner of Police'), ('SACP', 'Senior Assistant Commissioner'), ('ACP', 'Assistant Commissioner'), ('SSP', 'Senior Superintendent'), ('SP', 'Superintendent'), ('ASP', 'Assistant Superintendent'), ('INSP', 'Inspector'), ('A/INSP', 'Acting Inspector'), ('RSM', 'Regimental Sergeant Major'), ('S/SGT', 'Staff Sergeant'), ('SGT', 'Sergeant'), ('CPL', 'Corporal'), ('PC', 'Police Constable'), ('CIVILIAN', 'Civilian'), ('DR', 'Doctor')], default='PC', max_length=20)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('RPC', 'RPC / Unit Commander'), ('COMPENSATION_HQ', 'Compensation Desk HQ'), ('IGP', 'IGP'), ('IGP_DELEGATE', 'IGP Delegate'), ('COMMITTEE_MEMBER', 'Committee Member'), ('FINANCE', 'Finance')], default='RPC', max_length=20)),
                ('unit', models.CharField(blank=True, default='', max_length=255)),
                ('station', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'comp_users',
            },
        ),
    ]
