# Generated by Django 4.2.7 on 2026-04-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('RPC', 'RPC / Unit Commander'), ('COMPENSATION_HQ', 'Compensation Desk HQ'), ('COMPENSATION_HQ_CO', 'Compensation HQ - CO'), ('COMPENSATION_HQ_SO', 'Compensation HQ - SO'), ('COMPENSATION_HQ_CHIEF', 'Compensation HQ - Chief'), ('IGP', 'IGP'), ('IGP_DELEGATE', 'IGP Delegate'), ('COMMITTEE_MEMBER', 'Committee Member'), ('FINANCE', 'Finance')], default='RPC', max_length=50),
        ),
    ]
