# Generated by Django 4.2.7 on 2026-04-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('CP_HRM', 'Inspector General of Police'), ('DCP_HRM', 'Deputy CP_HRM'), ('CASP', 'Commissioner of Police'), ('SACP', 'Senior Assistant Commissioner'), ('ACP', 'Assistant Commissioner'), ('SSP', 'Senior Superintendent'), ('SP', 'Superintendent'), ('ASP', 'Assistant Superintendent'), ('INSP', 'Inspector'), ('A/INSP', 'Acting Inspector'), ('RSM', 'Regimental Sergeant Major'), ('S/SGT', 'Staff Sergeant'), ('SGT', 'Sergeant'), ('CPL', 'Corporal'), ('PC', 'Police Constable'), ('CIVILIAN', 'Civilian'), ('DR', 'Doctor')], default='PC', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('RPC', 'RPC / Unit Commander'), ('OCD', 'OCD / District Personnel Officer'), ('COMPENSATION_HQ', 'Compensation Desk HQ'), ('COMPENSATION_HQ_CO', 'Compensation HQ - CO'), ('COMPENSATION_HQ_SO', 'Compensation HQ - SO'), ('COMPENSATION_HQ_CHIEF', 'Compensation HQ - Chief'), ('CP_HRM', 'CP_HRM'), ('CP_HRM_DELEGATE', 'CP_HRM Delegate'), ('COMMITTEE_MEMBER', 'Committee Member'), ('FINANCE', 'Finance')], default='RPC', max_length=50),
        ),
    ]
