# Generated by Django 4.2.30 on 2026-05-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_rank_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('RPC', 'RPC / Unit Commander'), ('COMPENSATION_HQ', 'Compensation HQ'), ('COMPENSATION_CO', 'Compensation CO'), ('COMPENSATION_HQ_CHIEF', 'Compensation HQ - Chief'), ('CP_HRM', 'CP_HRM'), ('COMMITTEE_MEMBER', 'Committee Member')], default='RPC', max_length=50),
        ),
    ]
