# Generated by Django 4.2.30 on 2026-05-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('CP_ADMINISTRATION', 'Inspector General of Police'), ('DCP_ADMINISTRATION', 'Deputy CP_ADMINISTRATION'), ('CASP', 'Commissioner of Police'), ('SACP', 'Senior Assistant Commissioner'), ('ACP', 'Assistant Commissioner'), ('SSP', 'Senior Superintendent'), ('SP', 'Superintendent'), ('ASP', 'Assistant Superintendent'), ('INSP', 'Inspector'), ('A/INSP', 'Acting Inspector'), ('RSM', 'Regimental Sergeant Major'), ('S/SGT', 'Staff Sergeant'), ('SGT', 'Sergeant'), ('CPL', 'Corporal'), ('PC', 'Police Constable'), ('CIVILIAN', 'Civilian'), ('DR', 'Doctor')], default='PC', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('RPC', 'RPC / Unit Commander'), ('COMPENSATION_HQ', 'Compensation HQ'), ('COMPENSATION_CO', 'Compensation CO'), ('COMPENSATION_HQ_CHIEF', 'Compensation HQ - Chief'), ('CP_ADMINISTRATION', 'CP_ADMINISTRATION'), ('COMMITTEE_MEMBER', 'Committee Member')], default='RPC', max_length=50),
        ),
    ]
