# Generated by Django 6.0.2 on 2026-05-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_rank_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.TextField(blank=True, default=''),
        ),
    ]
