# Generated by Django 6.0.2 on 2026-05-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_profile_photo_user_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='check_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='nin',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
