# Generated by Django 6.0.2 on 2026-06-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_check_number_user_nin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('RPC', 'RPC / Unit Commander'), ('COMPENSATION_HQ', 'Compensation HQ'), ('COMPENSATION__HQ_CO', 'Compensation HQ - CO'), ('COMPENSATION__HQ_SO', 'Compensation HQ - SO'), ('COMPENSATION_HQ_CHIEF', 'Compensation HQ - Chief'), ('CP_ADMINISTRATION', 'CP_ADMINISTRATION'), ('COMMITTEE_MEMBER', 'Committee Member')], default='RPC', max_length=50),
        ),
    ]
