# Generated by Django 6.0.3 on 2026-06-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('RPC', 'RPC / Unit Commander'), ('COMPENSATION_HQ', 'Compensation HQ'), ('COMPENSATION_HQ_CO', 'Compensation HQ - CO'), ('COMPENSATION_HQ_SO', 'Compensation HQ - SO'), ('COMPENSATION_HQ_CHIEF', 'Compensation HQ - Chief'), ('CP_HRM', 'CP Human Resource Management'), ('CP_ADMINISTRATION', 'CP_ADMINISTRATION'), ('COMMITTEE_MEMBER', 'Committee Member')], default='RPC', max_length=50),
        ),
    ]
