# Generated by Django 6.0.6 on 2026-06-11 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_role'),
        ('accounts', '0010_user_must_change_password_alter_user_role'),
    ]

    operations = [
    ]
