# Generated by Django 6.0.2 on 2026-05-30 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompensationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('incident_type', models.CharField(choices=[('INJURY', 'Injury'), ('DEATH', 'Death')], max_length=6)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('CO_APPROVED', 'CO Approved'), ('SO_REVIEWED', 'SO Reviewed'), ('PENDING_CP_HRM', 'Pending CP_HRM'), ('INCOMPLETE', 'Incomplete'), ('RETURNED', 'Returned to RPC'), ('REJECTED', 'Rejected'), ('COMMITTEE_ASSIGNED', 'Committee Assigned'), ('ASSESSED', 'Assessed'), ('PAID', 'Paid')], default='SUBMITTED', max_length=20)),
                ('soldier_id', models.BigIntegerField(blank=True, null=True)),
                ('soldier_force_number', models.CharField(max_length=50)),
                ('soldier_full_name', models.CharField(max_length=300)),
                ('soldier_rank', models.CharField(max_length=50)),
                ('soldier_district', models.CharField(blank=True, default='', max_length=255)),
                ('incident_date', models.DateField()),
                ('incident_time', models.TimeField(blank=True, null=True)),
                ('incident_location', models.CharField(max_length=500)),
                ('nature_of_incident', models.TextField()),
                ('duty_context', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comments', models.TextField(blank=True, default='')),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('igp_approved_at', models.DateTimeField(blank=True, null=True)),
                ('igp_signature_hash', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('co_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('co_comments', models.TextField(blank=True, default='')),
                ('so_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('so_comments', models.TextField(blank=True, default='')),
                ('chief_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('chief_comments', models.TextField(blank=True, default='')),
                ('chief_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chief_reviewed_cases', to=settings.AUTH_USER_MODEL)),
                ('co_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_reviewed_cases', to=settings.AUTH_USER_MODEL)),
                ('igp_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='igp_approved_cases', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_cases', to=settings.AUTH_USER_MODEL)),
                ('so_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='so_reviewed_cases', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comp_cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('RPC', 'RPCROLE'), ('HQ_REPRESENTATIVE', 'HQ Representative'), ('OCD', 'OCD'), ('REGISTERED_DOCTOR', 'Registered Doctor')], max_length=30)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('appointment_letter_path', models.CharField(blank=True, default='', max_length=500)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committees_formed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='committee_assignments', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_members', to='compensation.compensationcase')),
            ],
            options={
                'db_table': 'comp_committee_members',
                'unique_together': {('case', 'role')},
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('from_status', models.CharField(blank=True, default='', max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('metadata', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='compensation.compensationcase')),
            ],
            options={
                'db_table': 'comp_audit_logs',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompensationFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('INJURY', 'Injury'), ('DEATH', 'Death')], max_length=6)),
                ('severity_class', models.CharField(choices=[('MINOR', 'Minor'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('CRITICAL', 'Critical'), ('PERMANENT', 'Permanent'), ('FATAL', 'Fatal')], max_length=10)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('multiplier', models.DecimalField(decimal_places=3, max_digits=6)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formulas_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comp_formulas',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_injury_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('final_severity_class', models.CharField(choices=[('MINOR', 'Minor'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('CRITICAL', 'Critical'), ('PERMANENT', 'Permanent'), ('FATAL', 'Fatal')], max_length=10)),
                ('suggested_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('requires_manual_review', models.BooleanField(default=False)),
                ('report_path', models.CharField(blank=True, default='', max_length=500)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='compensation.compensationcase')),
                ('formula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='compensation.compensationformula')),
            ],
            options={
                'db_table': 'comp_assessments',
            },
        ),
        migrations.CreateModel(
            name='MemberAssessmentInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injury_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('severity_class', models.CharField(choices=[('MINOR', 'Minor'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('CRITICAL', 'Critical'), ('PERMANENT', 'Permanent'), ('FATAL', 'Fatal')], max_length=10)),
                ('agreed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('assessment_notes', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_inputs', to='compensation.compensationcase')),
                ('committee_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_input', to='compensation.committeemember')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=60)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='compensation.compensationcase')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comp_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('OB_EXTRACT', 'OB Extract'), ('PF3', 'PF3'), ('PF90', 'PF90'), ('PF115', 'PF115'), ('MEDICAL_REPORT', 'Medical Report'), ('POSTMORTEM_REPORT', 'Postmortem Report'), ('DEATH_CERTIFICATE', 'Death Certificate'), ('NATIONAL_ID', 'National ID / Force ID')], max_length=30)),
                ('file', models.TextField()),
                ('file_content_type', models.CharField(default='application/pdf', max_length=100)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_docs', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_docs', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='compensation.compensationcase')),
            ],
            options={
                'db_table': 'comp_documents',
                'unique_together': {('case', 'doc_type')},
            },
        ),
    ]
