# Generated by Django 6.0.2 on 2026-06-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compensationcase',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('HQ_APPROVED', 'HQ Approved'), ('CO_APPROVED', 'CO Approved'), ('SO_REVIEWED', 'SO Reviewed'), ('PENDING_CP_HRM', 'Pending CP_HRM'), ('INCOMPLETE', 'Incomplete'), ('RETURNED', 'Returned to RPC'), ('REJECTED', 'Rejected'), ('COMMITTEE_ASSIGNED', 'Committee Assigned'), ('ASSESSED', 'Assessed'), ('PAID', 'Paid')], default='SUBMITTED', max_length=20),
        ),
    ]
