# Generated by Django 6.0.2 on 2026-06-05 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0002_alter_compensationcase_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compensationcase',
            name='hq_comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='compensationcase',
            name='hq_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compensationcase',
            name='hq_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hq_reviewed_cases', to=settings.AUTH_USER_MODEL),
        ),
    ]
