# Generated by Django 6.0.3 on 2026-06-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0003_compensationcase_hq_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensationcase',
            name='region',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
